### PR TITLE
Welcome screen for new users

### PR DESCRIPTION
**Pull request by kyledrake**
@violasong please review the copy, I'll merge when you OK.

### CODE REVIEW

**Comment by violasong** [comment]
@kyledrake This looks good, although I thought we were going to have a separate page for the welcome screen? I've been working on a mockup that is pretty different from the current /plan page (although, now that I think about it, it could serve as both the welcome and the plan page; not sure if that's ideal though). 

It needs more work, but here's what I have so far:
https://dl.dropboxusercontent.com/u/55342/temp/pricingwelcome03x.png

**Comment by kyledrake** [comment]
This is the "interim version" until your version is done (which of course already looks 1000 times better) ;)

**Comment by kyledrake** [comment]
I may just hold off until you're done and then implement your version, which is way better. I'll leave this as a branch PR for now.

**Comment by kyledrake** [comment]
@violasong Could you put a paypal link/button underneath the card as an alternate option? Thanks!

**Comment by violasong** [comment]
Yes, going to take a stab at that now.

**Comment by violasong** [comment]
@kyledrake Are we still going to offer the bitcoin lifer plan? (Btw, I thought we were on the Stripe beta for bitcoin - what happened with that?)

**Pull request merged**
