### PR TITLE
Add APNG

### PR DESCRIPTION
**Pull request by Winterhuman**
Adds APNG as a supported image format (although it *is* currently supported as just `image/png`, it'd be nice to have this extension as well to differentiate it for MIME-related situations).

### CODE REVIEW

**Comment by Winterhuman** [comment]
@kyledrake Friendly ping

**Comment by Winterhuman** [comment]
@kyledrake Friendly ping

**Comment by kyledrake** [comment]
I'll merge this here. It also needs to be added to the mime type for the cdn (different file, no ETA on when it will be deployed yet). So don't expect it to work right away.

FWIW I think APNG is a terrible idea and I really don't understand why they decided to implement it. GIF too is very much an old and obsolete way to do animated frames. I've considered allowing MP4 for Neocities just to get people to stop using them (MP4 does between frame encoding that allows for much smaller file sizes). We have had abuse issues with GIFs (people using them for mini-videos causing disproportionate load on the CDN). I may have to introduce a special file size limitation for them in the future to prevent this sort of activity (10MB? No idea).

**Comment by Winterhuman** [comment]
The main reason I use APNG is because, for all but a few of the animated images on my site, it's actually smaller than GIF. I wrote a script for [finding minimum sized images here](https://gist.github.com/Winterhuman/21d7b148db40ff041f397b07a7aafb83) which demonstrates this (every tool variation in there can be the smallest encoding, which yeah, is kinda painful).

Perhaps instead of a size constraint, you could implement a runtime limit instead (So short, but complex GIFs aren't affected)? e.g. Denying GIFs longer than 15 seconds (using the sum of the frame durations).

**Comment by kyledrake** [comment]
Thanks for the feedback. It would be prohibitive difficult and potentially dangerous to implement something to specifically parse out and check frame numbers in real time on upload, size is the only practical option here unfortunately. That code is pretty (too) complex as-is and I'm very careful about making substantial changes to it.

**Pull request merged**
