### PR TITLE
Markup & a11y updates

### PR DESCRIPTION
**Pull request by scottaohara**
The beginning of what i'm hoping to be a much larger effort to revise the site's markup and to add in appropriate accessibility (aria) attributes wherever possible.

### CODE REVIEW

**Comment by scottaohara** [comment]
@kyledrake any idea what this is failing on?  I honestly don't understand what the error report is saying, and my updates were purely in the DOM / making the markup better for accessibility.

**Comment by kyledrake** [comment]
Whoa, somehow I missed this PR, my apologies! Let me sit down and give this proper inspection this weekend.

Welcome back. :)

**Comment by scottaohara** [comment]
much appreciated and thank you.

No worries on missing it. I'm looking forward to diving into this more.

**Comment by scottaohara** [comment]
heya @kyledrake 
just wanted to poke you one more time on what these failures actually mean. Again, no idea why this would fail as all I did was make the markup more accessible.

**Pull request closed without merging**
